[package]
name = "poc-tree-size-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.33"
egui_extras = { version = "0.33", features = ["default"] }
rfd = "0.15"
jwalk = "0.8"
blake3 = { version = "1", features = ["prefer_intrinsics"] }
crossbeam-channel = "0.5"
anyhow = "1"

[dev-dependencies]
tempfile = "3"

[profile.release]
opt-level = 3
lto = "thin"
